---
- name: Manage instance states
  hosts: localhost
  gather_facts: False

  tasks:
    - name: "Apply state to instances: {{ NAME }} -> {{ STATE }}"
      gce:
        name: "{{ NAME }}"
        state: "{{ STATE }}"
